# Generated by Django 4.2.11 on 2024-05-09 16:09

import colorfield.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                (
                    'color',
                    colorfield.fields.ColorField(
                        default='#FFFFFF', image_field=None, max_length=25, samples=None, verbose_name='color'
                    ),
                ),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Worktable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'session_key',
                    models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='session'),
                ),
                (
                    'user',
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='user',
                    ),
                ),
            ],
            options={
                'verbose_name': 'worktable',
                'verbose_name_plural': 'worktables',
                'ordering': ['user'],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('text', models.TextField(blank=True, null=True, verbose_name='text')),
                ('words', models.PositiveIntegerField(default=0, verbose_name='Quantity of words in text')),
                (
                    'unique_words',
                    models.PositiveIntegerField(default=0, verbose_name='Quantity of unique words in text'),
                ),
                ('is_archived', models.BooleanField(default=False, verbose_name='archived')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                (
                    'category',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to='notes.category',
                        verbose_name='category',
                    ),
                ),
                (
                    'worktable',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='notes.worktable', verbose_name='worktable'
                    ),
                ),
            ],
            options={
                'verbose_name': 'note',
                'verbose_name_plural': 'notes',
                'ordering': ['-created'],
            },
        ),
        migrations.AddField(
            model_name='category',
            name='worktable',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='notes.worktable', verbose_name='worktable'
            ),
        ),
    ]
