# Generated by Django 4.2.11 on 2024-05-02 13:49

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                (
                    'color',
                    colorfield.fields.ColorField(
                        default='#FFFFFF', image_field=None, max_length=25, samples=None, verbose_name='color'
                    ),
                ),
                (
                    'worktable',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='notes.worktable', verbose_name='worktable'
                    ),
                ),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ['title'],
            },
        ),
    ]
