# Generated by Django 4.2.11 on 2024-05-02 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('notes', '0002_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('text', models.TextField(blank=True, null=True, verbose_name='text')),
                ('is_archived', models.BooleanField(default=False, verbose_name='archived')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                (
                    'category',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to='notes.category',
                        verbose_name='category',
                    ),
                ),
                (
                    'worktable',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='notes.worktable', verbose_name='worktable'
                    ),
                ),
            ],
        ),
    ]
