# Generated by Django 4.2.11 on 2024-05-03 12:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('notes', '0003_note'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['-created'], 'verbose_name': 'note', 'verbose_name_plural': 'notes'},
        ),
    ]
