# Generated by Django 4.2.11 on 2024-05-03 12:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('notes', '0004_alter_note_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worktable',
            name='session',
        ),
        migrations.AddField(
            model_name='worktable',
            name='session_key',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='session'),
        ),
    ]
