# Generated by Django 4.2.11 on 2024-05-07 10:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('notes', '0005_remove_worktable_session_worktable_session_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='unique_words',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantity of unique words in text'),
        ),
        migrations.AddField(
            model_name='note',
            name='words',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantity of words in text'),
        ),
        migrations.AlterField(
            model_name='worktable',
            name='session_key',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='session'),
        ),
    ]
